# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gpsinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='gpsinfo.proto',
  package='xyz.sx.collectorcore.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rgpsinfo.proto\x12\x1dxyz.sx.collectorcore.protobuf\"e\n\x07GpsData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x10\n\x08latitude\x18\x02 \x01(\x01\x12\x11\n\tlongitude\x18\x03 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x04 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x01\x62\x06proto3')
)




_GPSDATA = _descriptor.Descriptor(
  name='GpsData',
  full_name='xyz.sx.collectorcore.protobuf.GpsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='xyz.sx.collectorcore.protobuf.GpsData.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='xyz.sx.collectorcore.protobuf.GpsData.latitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='xyz.sx.collectorcore.protobuf.GpsData.longitude', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='xyz.sx.collectorcore.protobuf.GpsData.altitude', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='xyz.sx.collectorcore.protobuf.GpsData.accuracy', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['GpsData'] = _GPSDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GpsData = _reflection.GeneratedProtocolMessageType('GpsData', (_message.Message,), dict(
  DESCRIPTOR = _GPSDATA,
  __module__ = 'gpsinfo_pb2'
  # @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.GpsData)
  ))
_sym_db.RegisterMessage(GpsData)


# @@protoc_insertion_point(module_scope)
