# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macinfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='macinfo.proto',
  package='xyz.sx.collectorcore.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmacinfo.proto\x12\x1dxyz.sx.collectorcore.protobuf\"$\n\x07MacPair\x12\x0b\n\x03mac\x18\x01 \x01(\t\x12\x0c\n\x04rssi\x18\x02 \x01(\x05\"V\n\x0bMacScanLine\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x34\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32&.xyz.sx.collectorcore.protobuf.MacPairb\x06proto3')
)




_MACPAIR = _descriptor.Descriptor(
  name='MacPair',
  full_name='xyz.sx.collectorcore.protobuf.MacPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mac', full_name='xyz.sx.collectorcore.protobuf.MacPair.mac', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rssi', full_name='xyz.sx.collectorcore.protobuf.MacPair.rssi', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=84,
)


_MACSCANLINE = _descriptor.Descriptor(
  name='MacScanLine',
  full_name='xyz.sx.collectorcore.protobuf.MacScanLine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='xyz.sx.collectorcore.protobuf.MacScanLine.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='xyz.sx.collectorcore.protobuf.MacScanLine.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=172,
)

_MACSCANLINE.fields_by_name['data'].message_type = _MACPAIR
DESCRIPTOR.message_types_by_name['MacPair'] = _MACPAIR
DESCRIPTOR.message_types_by_name['MacScanLine'] = _MACSCANLINE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MacPair = _reflection.GeneratedProtocolMessageType('MacPair', (_message.Message,), dict(
  DESCRIPTOR = _MACPAIR,
  __module__ = 'macinfo_pb2'
  # @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.MacPair)
  ))
_sym_db.RegisterMessage(MacPair)

MacScanLine = _reflection.GeneratedProtocolMessageType('MacScanLine', (_message.Message,), dict(
  DESCRIPTOR = _MACSCANLINE,
  __module__ = 'macinfo_pb2'
  # @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.MacScanLine)
  ))
_sym_db.RegisterMessage(MacScanLine)


# @@protoc_insertion_point(module_scope)
