# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: samplesseq.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sensorcollection_pb2 as sensorcollection__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='samplesseq.proto',
  package='xyz.sx.collectorcore.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10samplesseq.proto\x12\x1dxyz.sx.collectorcore.protobuf\x1a\x16sensorcollection.proto\"V\n\x07Samples\x12\x0c\n\x04\x64\x65sc\x18\x01 \x01(\t\x12=\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32/.xyz.sx.collectorcore.protobuf.SensorCollectionb\x06proto3')
  ,
  dependencies=[sensorcollection__pb2.DESCRIPTOR,])




_SAMPLES = _descriptor.Descriptor(
  name='Samples',
  full_name='xyz.sx.collectorcore.protobuf.Samples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='desc', full_name='xyz.sx.collectorcore.protobuf.Samples.desc', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='xyz.sx.collectorcore.protobuf.Samples.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=161,
)

_SAMPLES.fields_by_name['data'].message_type = sensorcollection__pb2._SENSORCOLLECTION
DESCRIPTOR.message_types_by_name['Samples'] = _SAMPLES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Samples = _reflection.GeneratedProtocolMessageType('Samples', (_message.Message,), dict(
  DESCRIPTOR = _SAMPLES,
  __module__ = 'samplesseq_pb2'
  # @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.Samples)
  ))
_sym_db.RegisterMessage(Samples)


# @@protoc_insertion_point(module_scope)
