# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensorcollection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import macinfo_pb2 as macinfo__pb2
import gpsinfo_pb2 as gpsinfo__pb2
import vector3_pb2 as vector3__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensorcollection.proto',
  package='xyz.sx.collectorcore.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16sensorcollection.proto\x12\x1dxyz.sx.collectorcore.protobuf\x1a\rmacinfo.proto\x1a\rgpsinfo.proto\x1a\rvector3.proto\"\xce\x02\n\x10SensorCollection\x12\x38\n\x04wifi\x18\x01 \x03(\x0b\x32*.xyz.sx.collectorcore.protobuf.MacScanLine\x12\x33\n\x03gps\x18\x02 \x03(\x0b\x32&.xyz.sx.collectorcore.protobuf.GpsData\x12\x33\n\x03\x61\x63\x63\x18\x03 \x03(\x0b\x32&.xyz.sx.collectorcore.protobuf.Vector3\x12\x33\n\x03gyr\x18\x04 \x03(\x0b\x32&.xyz.sx.collectorcore.protobuf.Vector3\x12\x33\n\x03mag\x18\x05 \x03(\x0b\x32&.xyz.sx.collectorcore.protobuf.Vector3\x12\x0b\n\x03ori\x18\x06 \x03(\x02\x12\x0c\n\x04step\x18\x07 \x03(\x03\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x62\x06proto3')
  ,
  dependencies=[macinfo__pb2.DESCRIPTOR,gpsinfo__pb2.DESCRIPTOR,vector3__pb2.DESCRIPTOR,])




_SENSORCOLLECTION = _descriptor.Descriptor(
  name='SensorCollection',
  full_name='xyz.sx.collectorcore.protobuf.SensorCollection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wifi', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.wifi', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.gps', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.acc', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gyr', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.gyr', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mag', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.mag', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ori', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.ori', index=5,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.step', index=6,
      number=7, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='xyz.sx.collectorcore.protobuf.SensorCollection.timestamp', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=437,
)

_SENSORCOLLECTION.fields_by_name['wifi'].message_type = macinfo__pb2._MACSCANLINE
_SENSORCOLLECTION.fields_by_name['gps'].message_type = gpsinfo__pb2._GPSDATA
_SENSORCOLLECTION.fields_by_name['acc'].message_type = vector3__pb2._VECTOR3
_SENSORCOLLECTION.fields_by_name['gyr'].message_type = vector3__pb2._VECTOR3
_SENSORCOLLECTION.fields_by_name['mag'].message_type = vector3__pb2._VECTOR3
DESCRIPTOR.message_types_by_name['SensorCollection'] = _SENSORCOLLECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorCollection = _reflection.GeneratedProtocolMessageType('SensorCollection', (_message.Message,), dict(
  DESCRIPTOR = _SENSORCOLLECTION,
  __module__ = 'sensorcollection_pb2'
  # @@protoc_insertion_point(class_scope:xyz.sx.collectorcore.protobuf.SensorCollection)
  ))
_sym_db.RegisterMessage(SensorCollection)


# @@protoc_insertion_point(module_scope)
